# Configuration for running GitHub actions
#  see https://docs.github.com/en/actions/guides/setting-up-continuous-integration-using-workflow-templates

name: CI (latest)

on:
  push:
  pull_request:
  schedule:
    - cron:  '42 5 * * *'

jobs:

  cgl:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '7.4' ]
        minMax: [ 'composerInstallMax' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composerValidate

      - name: Composer install
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s ${{ matrix.minMax }}

      - name: cgl
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s cgl -v -n

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: phpstan
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s phpstan -e "-c ../phpstan.neon"
